### ISSUE TITLE
Scan QR Code! and Waiting for click to reload QR code!

### ISSUE THREAD

**Issue by fyudelgado** [efraimrodrigues/WhaPy#2]
Hi there,
I'm running the sample file that comes with the code distribution.

The sample code has the follow coding:

```

import whapy

wap = whapy.WhaPy(whapy.Browser.firefox,True)

qrfile = open("/home/whapy/Proyects/WhaPy/qr.gif", "w")
qrfile.write(wap.get_qrcode())
qrfile.close()

print("QR File Saved")

```

But the file is not wrote. The documentation does not describe which kind of data is returned from wap.get_qrcode()

I'm using python 3 and the selenium and whapy was installed successful.

I'm unable to activate the browsing selenium from the QR code generated, so where is this QR stored once the whapy sample.py file is running?

Regards,
Francisco Yu

**Comment by efraimrodrigues** [comment]
I'm sorry but due WhatsApp recent updates to the whatsapp web service WhaPy has been discontinued.
